import { Metadata } from "next";
import { notFound } from "next/navigation";
import React from "react";

export const metadata = {
  title: "Hello",
  description: "Generated by Hello",
};

export default function PageIndex({ params }) {
  // return notFound();
  console.log(params);
  return (
    <main className="flex min-h-screen flex-col items-center justify-between py-10">
      <div className="flex flex-col space-y-8 pb-10 pt-12 md:pt-24">
        <h1 className="text-center text-3xl font-bold text-gray-900 md:text-5xl md:leading-10">
          Page {params.pageSlug}
        </h1>
        <div>
          <p className="mx-auto max-w-4xl text-center text-base text-gray-600 md:text-xl">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore
            veritatis voluptates neque itaque repudiandae sint, explicabo
            assumenda quam ratione placeat?
          </p>
        </div>
      </div>
    </main>
  );
}
