import PageTemplate from "@/components/template/page-template";
import { getPageByUri, pagePathBySlug } from "@/lib/pages";
import { notFound } from "next/navigation";
import "@/app/page.css";

export const metadata = {
    title: "Hello",
    description: "Generated by Hello",
};

export default async function PageIndex({ params }) {
    const { parentPage } = params
    let pageUri = pagePathBySlug(parentPage);
    const { page } = await getPageByUri(pageUri);
    if (!page) notFound();

    return (
        <PageTemplate page={page} />
    );
}